Additional Config
otland/forgottenserver pull request #3060
Opened 2020-05-21 02:01 UTC by EPuncker

***names and location are subject to change*** (suggestions are welcome)

- Added !buyhouse level and premium requirement config (#2879 )
- Changed it to removeTotalMoney on both buyhouse and buy premium commands
- Added setting to enable/disable change sex and buy premium command
- Moved a few talkaction settings to the new additional script config file

- that print at the end of file was just for debugging, it may me removed

***names and location are subject to change*** (suggestions are welcome)

2020-05-21 05:16 UTC, MillhioreBT commented
I don't like the idea of ​​the `script config.lua` file but I do like the reason.

2020-05-22 02:58 UTC, DSpeichert commented
The second config is quite confusing.
Can't we just add additional options to the "main" config.lua that the C++ code will simply ignore?

2020-05-22 12:24 UTC, soul4soul commented
I'm don't like the idea of combining all of the scripts with a common config file. I do like some of the enhancements made to the individual scripts and would like to see the specific configs stay in those files. EG. keep the new config added for dice on depot in the dice.lua file.

2020-05-22 12:39 UTC, EPuncker commented
> The second config is quite confusing.
> Can't we just add additional options to the "main" config.lua that the C++ code will simply ignore?

I didn't knew it was possible 😄 gonna do it

2020-06-10 02:43 UTC, DSpeichert commented
So config.lua is implicitly available throughout Lua scope? I don't see the libs/ executing it anywhere.

2020-06-10 06:10 UTC, EPuncker commented
> So config.lua is implicitly available throughout Lua scope? I don't see the libs/ executing it anywhere.

yeah its kinda weird, there are some that works and some that don't, will investigate further

2020-12-27 06:10 UTC, DSpeichert requested changes

2020-12-27 06:10 UTC, DSpeichert commented on config.lua.dist
> +useWormsToFishing = true
```suggestion
useWormsForFishing = true
```

2020-12-28 11:40 UTC, nekiro commented
Hoenstly I find these redundant and config bloating, why creating config values for easily editable lua scripts?

2020-12-28 22:27 UTC, EPuncker commented
> Honestly I find these redundant and config bloating, why creating config values for easily editable lua scripts?
> Some of them like death related are okay, but "useWormsForFishing" is kind of redundant to me.

I find it better to have all of them in a single place, but yes that is kinda of a matter of opinion

2020-12-30 04:22 UTC, peonso commented
Bloating. Config should only deal with server setup (map name/ip/database) and hardcoded stuff. If you add everysingle script option to config.lua because someone want it there we can reach thousand lines really fast.

2021-02-10 01:39 UTC, DSpeichert commented
I have reconsidered my earlier opinion and decided that config.lua is not the place to gather all config options from the datapack.
IMHO it would be clearer to the user when config.lua focuses of the built-in engine features, which generally means fewer and fewer things as things move to Lua.

What we need instead is a good datapack README, showing which scripts are responsible for which behavior, so that a user can go and reconfigure them.

I'm primarily thinking about TFS as an engine that can be used with the widest range of datapacks, therefore comingling the core config and datapack config is confusing.

2021-02-13 21:06 UTC, closed without merging