Compat update
otland/forgottenserver pull request #3110
Opened 2020-06-30 02:08 UTC by EPuncker

lets make it friendly to 0.4 users to migrate to 1.x

2020-06-30 16:42 UTC, luanluciano93 commented
In the functions **getPlayerGUIDByName** and **getAccountNumberByPlayerName** replace the **getDataInt** with **getNumber**

2020-06-30 16:45 UTC, luanluciano93 commented
In data/globalevents/scripts/record.lua change **broadcastMessage** with **Game.broadcastMessage**

2020-06-30 23:52 UTC, EPuncker commented
done

2020-07-08 23:01 UTC, nekiro commented on data/lib/compat/compat.lua
> +function doPlayerSave(cid, ...) local p = Player(cid) return p and p:savePlayer(shallow or false) or false end
player:save()?

2020-07-08 23:01 UTC, nekiro commented on data/lib/compat/compat.lua
> +function doPlayerSetMaxCapacity(cid, cap) local p = Player(cid) return p and p:setMaxCap(cap) or false end
setMaxCap does not exist

2020-07-08 23:02 UTC, nekiro commented on data/lib/compat/compat.lua
> +function doPlayerSetSpecialDescription(cid, desc) local p = Player(cid) return p and p:setSpecialDescription(desc) or false end
setSpecialDescription does not exist

2020-07-08 23:02 UTC, nekiro commented on data/lib/core/player.lua
> +	if(amount > 0) then
if amount > 0 then

2020-07-08 23:03 UTC, nekiro commented on data/lib/core/player.lua
> +	if (weapon) then
if weapon then

2020-07-11 00:49 UTC, luanluciano93 commented
Change **isItemFluidContainer(itemid)** to ### ItemType(itemId):isFluidContainer()

> https://github.com/otland/forgottenserver/blob/ec0fd327146fe51c35165c57fc564a47fbad160f/data/npc/lib/npcsystem/modules.lua#L1001

2020-07-13 06:39 UTC, EPuncker commented
> ItemType(itemId):isFluidContainer()

thanks, keep it coming 😄

2020-08-14 05:42 UTC, EPuncker commented
this is pretty much ready, and I wanted to push it to 1.4 since it is kinda useful in order to make it easier for people to migrate from 0.x to 1.x so I'd like to get a review from developers

2020-08-24 02:06 UTC, DSpeichert commented
Is there any specific 0.4-style datapack you can find that wouldn't normally work with TFS master version but after this change it would? That would be a good test case and great example for when we release next version.

2020-08-24 04:30 UTC, ranisalt requested changes

2020-08-24 04:30 UTC, ranisalt commented on data/global.lua
> +	return (((50 * level * level * level) - (150 * level * level) + (400 * level))/3)
Parenthesis are inconsistent, and most of them are not needed at all.

```lua
return (50 * level * level * level - 150 * level * level + 400 * level) / 3
```

2020-08-24 16:12 UTC, EPuncker commented
> Is there any specific 0.4-style datapack you can find that wouldn't normally work with TFS master version but after this change it would? That would be a good test case and great example for when we release next version.

no, I made it specially by searching function names on otland search and seeing usage and errors

2020-08-24 18:35 UTC, ranisalt submitted a review, later dismissed
:+1:

2020-10-26 00:54 UTC, nekiro reviewed
just trying to unlock my request changes

2020-10-26 00:54 UTC, nekiro approved these changes
just ublocking my review,

2020-10-26 02:43 UTC, Znote approved these changes

2020-11-02 01:57 UTC, DSpeichert commented on data/lib/compat/compat.lua
> +if unpack == nil then unpack = table.unpack end
nice!

2020-11-05 03:07 UTC, DSpeichert approved these changes

2020-11-05 03:09 UTC, merged