Added float support to config.lua
otland/forgottenserver pull request #3157
Opened 2020-08-06 17:53 UTC by EPuncker

- added float support to config.lua
- moved sharedExperienceMultiplier from \data\events\scripts\party.lua to config.lua as example

code by @infernumx

2020-08-06 18:14 UTC, Shawak commented on src/configmanager.cpp
> +	floating[SHARED_EXPERIENCE_MULTIPLIER] = getGlobalFloat(L, "sharedExperienceMultiplier", 1.20);
1.2f

2020-08-06 18:47 UTC, EPuncker commented on src/configmanager.cpp
> +	floating[SHARED_EXPERIENCE_MULTIPLIER] = getGlobalFloat(L, "sharedExperienceMultiplier", 1.20);
thanks!

2020-12-12 23:12 UTC, DSpeichert submitted a review, later dismissed

2021-01-07 04:15 UTC, peonso commented
While I like it a lot, I'm bothered by consistency, why exp, loot and skill rates aren't floats either? They should and this change might lead people to believe they are.

2021-03-06 07:38 UTC, danyelvarejao submitted a review, later dismissed

2021-07-29 08:29 UTC, nekiro commented
> While I like it a lot, I'm bothered by consistency, why exp, loot and skill rates aren't floats either? They should and this change might lead people to believe they are.

That's great observation. We can update them later in next prs. This one is fine as it is, to me at least.

2021-07-29 08:31 UTC, nekiro submitted a review, later dismissed

2021-07-30 21:02 UTC, DSpeichert approved these changes

2021-07-30 21:03 UTC, DSpeichert commented
I like Float support but I'm not sure if we want to move everything to config.lua.

2021-07-30 21:09 UTC, EPuncker commented
> I like Float support but I'm not sure if we want to move everything to config.lua.

that entry was added just as example, should I remove it?

2021-07-31 01:37 UTC, DSpeichert commented
> that entry was added just as example, should I remove it?

Hard to say, it's a nice representation of what can be done now, but it could be unnecessary to move things to config.lua and also confusing if other values can't be floats. Maybe remove it and we keep it as a "hidden feature" for now?

2021-07-31 06:15 UTC, EPuncker commented
> > that entry was added just as example, should I remove it?
> 
> Hard to say, it's a nice representation of what can be done now, but it could be unnecessary to move things to config.lua and also confusing if other values can't be floats. Maybe remove it and we keep it as a "hidden feature" for now?

done

2021-07-31 14:24 UTC, DSpeichert approved these changes

2021-07-31 14:29 UTC, nekiro requested changes

2021-07-31 14:29 UTC, nekiro commented on src/configmanager.h
> +			LAST_FLOATING_CONFIG
arrays cant be zero sized, you have to mark this 1 or add at least one config enum

2021-08-01 04:08 UTC, EPuncker commented
what about we add it when it is useful at all? :D

2021-08-01 04:08 UTC, closed without merging