Prevent moving items if player is not invited to house
otland/forgottenserver pull request #3159
Opened 2020-08-11 21:18 UTC by nekiro

You shouldn't be able to remove/move items out of house if you are not invited (open door scenario).

2020-08-29 17:53 UTC, DSpeichert submitted a review, later dismissed

2020-08-29 21:45 UTC, ranisalt commented
How can you move items inside a house you are not invited to? How do you get inside it to begin with?

2020-08-29 21:46 UTC, nekiro commented
> How can you move items inside a house you are not invited to? How do you get inside it, to begin with?

Open door

2020-08-29 23:50 UTC, mattyx14 submitted a review, later dismissed

2020-08-30 03:19 UTC, ranisalt commented
> Open door

As far as I'm concerned even with an open door you can not enter a house if not invited.

2020-08-30 04:49 UTC, EPuncker commented
> > Open door
> 
> As far as I'm concerned even with an open door you can not enter a house if not invited.

I think nekiro is talking about this scenario:
![2020-08-30 01_48_48](https://user-images.githubusercontent.com/4684880/91651434-04b73980-ea63-11ea-9023-3068cfe2e397.png)

2020-08-30 20:25 UTC, ranisalt commented
Ah, I see, that's clear to me now, sorry for the confusion.

2020-08-30 23:09 UTC, EvilHero90 approved these changes

2020-08-30 23:46 UTC, EPuncker submitted a review, later dismissed

2020-08-31 17:51 UTC, soul4soul commented
In cipbia I think you are allowed to move items from an open door. The exception is tile carpets. I recently remember picking up vials from an open door in cipbia.

2020-09-18 12:31 UTC, nekiro commented
> In cipbia I think you are allowed to move items from an open door. The exception is tile carpets. I recently remember picking up vials from an open door in cipbia.

Yeah, checked it today, you cannot move carpets, but vials or other stuff can be moved.

2020-10-07 17:14 UTC, EPuncker requested changes

2020-10-07 17:14 UTC, EPuncker commented on src/configmanager.cpp
> +	boolean[ONLY_INVITED_CAN_MOVE_HOUSE_ITEMS] = getGlobalBoolean(L, "onlyInvitedCanMoveHouseItems", true);
seems like a little mistake 😜

2020-10-07 17:18 UTC, nekiro commented on src/configmanager.cpp
> +	boolean[ONLY_INVITED_CAN_MOVE_HOUSE_ITEMS] = getGlobalBoolean(L, "onlyInvitedCanMoveHouseItems", true);
You are looking at outdated changes

2020-10-07 20:59 UTC, EPuncker approved these changes

2020-10-18 21:46 UTC, merged

2020-10-28 03:26 UTC, Diego-OT commented
There is a bug when player "Use with" item

https://gyazo.com/2d5ca5a042bbdd1c5191a1dde192fb44

2020-10-28 03:35 UTC, EPuncker commented
@nekiro could you check this please? I can't right now

2020-10-28 10:15 UTC, nekiro commented
@EPuncker no, it does not happen.

2021-10-20 12:09 UTC, felipepips commented
> You shouldn't be able to remove items from house if you are not invited (open door scenario).

Hello. I did all the changes and now i actually cant move items from house tiles, but if this item is a container (bag, backpack) i can open and take items from inside.. any fix for that? Thanks

2021-11-02 15:12 UTC, Emilianenko commented
> > You shouldn't be able to remove items from house if you are not invited (open door scenario).
> 
> Hello. I did all the changes and now i actually cant move items from house tiles, but if this item is a container (bag, backpack) i can open and take items from inside.. either if the item in door tile is something useable (food) i can use (eat).. any fix for that? Thanks

@nekiro @EPuncker

2021-11-02 15:17 UTC, EPuncker commented
> > You shouldn't be able to remove items from house if you are not invited (open door scenario).
> 
> Hello. I did all the changes and now i actually cant move items from house tiles, but if this item is a container (bag, backpack) i can open and take items from inside.. either if the item in door tile is something useable (food) i can use (eat).. any fix for that? Thanks

hello, please open an issue so this can be taken a look in the future