Additional checks for unsigned integers to avoid underflow and overflow
otland/forgottenserver pull request #3197
Opened 2020-10-23 23:22 UTC by nekiro

Additional checks in getNumber<T>(L, arg)

Prints a handy warnings if unsigned integer is < 0 or > max type value

![image](https://user-images.githubusercontent.com/14142246/97061500-62658f00-1597-11eb-9289-28e93e2a81cd.png)

2020-10-24 03:18 UTC, DSpeichert submitted a review, later dismissed

2020-10-26 01:11 UTC, DSpeichert approved these changes

2020-10-26 05:28 UTC, Znote approved these changes

2020-10-28 03:24 UTC, DSpeichert commented
Note the potential performance impact as noted by Mark.

2021-02-09 04:31 UTC, MillhioreBT commented
This implementation causes performance to be compromised, in fact it drops by about 70%~

You can try the following code and you can compare the time, you will notice that with this implementation increases the time dramatically.

```c++
time_t now = OTSYS_TIME();
for (int i = 0; i < 1000000000; i++) {
    getNumber<time_t>(L, 2);
}
std::cout << "Test getNumber of LuaInterface: " << std::setprecision(15) << (double)(OTSYS_TIME() - now) << std::endl;
```

I know that there are never cases in which `getNumber` is called with this frequency, I don't know if it is worth it, Someone else should do tests, I don't know if the tests I did were enough or well done

2021-02-10 17:09 UTC, yamaken93 commented
@MillhioreBT are you testing with release version all optimizations enabled?

2021-02-11 04:23 UTC, MillhioreBT commented
> @MillhioreBT are you testing with release version all optimizations enabled?

Of course, the code is clear to the naked eye, obviously it takes more time, but it wouldn't be a big problem really, since at small scales there doesn't seem to be a much difference.
If calling `getNumber(L, 2);` 1000000000 times requires 3 seconds, with these modifications it will require approximately 5 seconds, but let's face it, when can this situation occur?

2021-03-03 21:43 UTC, MillhioreBT commented
It would be amazing to have the opinion of @marksamman about this

2021-07-29 08:07 UTC, nekiro commented
> It would be amazing to have the opinion of @marksamman about this

Is it dropping performance in general or is it with invalid value only?

2021-07-30 03:16 UTC, DSpeichert approved these changes

2021-07-30 06:40 UTC, Zbizu commented
imo not worth losing 70% of the performance for that. Should be optional in compiler settings.

2021-07-30 06:43 UTC, Zbizu requested changes
imo not worth losing 70% of the performance for that. Should be optional in compiler settings.

2022-02-06 17:16 UTC, DSpeichert commented
The test conducted by @MillhioreBT is synthetic, not representative of what datapacks in the wild do.
In the absence of other comments over the time, I'm willing to take it as a feature unless real-world performance problems are reported.

2022-02-06 17:18 UTC, merged

2022-02-12 12:28 UTC, dex-89 commented
![image](https://user-images.githubusercontent.com/67392692/153711327-96b306a3-230d-4ef8-9ac5-2629bdeac8aa.png)