Update FindLuaJIT.cmake
otland/forgottenserver pull request #3214
Opened 2020-11-12 14:50 UTC by xitobuh

addressing error:

-- Could NOT find LuaJIT (missing: LUA_INCLUDE_DIR)
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Lua (missing: LUA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLua.cmake:113 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:43 (find_package)

2020-11-17 00:21 UTC, DSpeichert commented
What platform does your error appear on?

2020-11-17 11:51 UTC, xitobuh commented
Ubuntu 20.10 docker

tis 17 nov. 2020 kl. 01:21 skrev Daniel Speichert <notifications@github.com
>:

> What platform does your error appear on?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/otland/forgottenserver/pull/3214#issuecomment-728486726>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANM6AAAW376SZJQKQF6ZWOTSQG6YFANCNFSM4TTMEFYA>
> .
>

2020-11-27 04:16 UTC, ericlancebrown requested changes
The original code was the correct format. It is for finding luajit when using vcpkg. 

It is likely you either do not have lua installed or the lib directory changed in the ubuntu 20.10 installation.

If you ended up building it, would you mind posting the output of:

```
ldd tfs
```

Or whatever the name of the executable is?

2020-11-27 04:16 UTC, ericlancebrown commented on cmake/FindLuaJIT.cmake
> -  PATH_SUFFIXES include/luajit-2.0 include/luajit-2.1 include luajit
This is the correct format. It is for finding the luajit headers on vcpkg.

2021-03-14 03:24 UTC, DSpeichert commented
If the issue still persists, please open a bug report with the details.

2021-03-14 03:24 UTC, closed without merging