Container overflow fix
otland/forgottenserver pull request #3228
Opened 2020-11-21 02:20 UTC by Zbizu

regarding #3225

credits [SaiyansKing/optimized_forgottenserver@a205b5f](https://github.com/SaiyansKing/optimized_forgottenserver/commit/a205b5f033e88fe217721116dd623b6ef253bb43)

tests performed:

picking up items
/i pickupable item
/i non-pickupable item

in these situations:
- player has no eq
- player has no eq but has a container
- player has eq but no container
- player has both eq and a container
- player has a overloaded container
- player has multiple overloaded containers in his eq

result:
- items cannot be picked up if there is no room in container
- created items get dropped on the floor with no freeze

2020-11-26 23:15 UTC, ericlancebrown approved these changes
Code looks fine syntax wise.

Was able to build perfectly fine as well on Ubuntu 20.04 as well as 18.04.

2020-12-05 09:46 UTC, EPuncker approved these changes

2020-12-12 16:48 UTC, Dip-Set1 commented
This will create a few problems.. if player buys item from an NPC and has multiple containers (bp inside bp), even if 2nd bp has empty slots, the items will just delete

2021-01-17 16:56 UTC, EPuncker commented
> This will create a few problems.. if player buys item from an NPC and has multiple containers (bp inside bp), even if 2nd bp has empty slots, the items will just delete

I confirm this, items are getting deleted, to reproduce:

1. create two backpacks
2. fill the first one with 19 brass armor (or any other non stackable item)
3. open trade with an npc and buy any item
4. it will be deleted instead of being added to the empty backpack

2021-01-17 16:56 UTC, EPuncker requested changes
the issue above need to be fixed

2021-01-17 18:03 UTC, closed without merging