Use lowercase names too
otland/forgottenserver pull request #3393
Opened 2021-04-04 21:51 UTC by MillhioreBT

### Pull Request Prelude
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
In previous versions you could write the names of the vocations in lowercase, at this time the name must exactly match the name, which is not very comfortable.

### Example
`spell:vocation("sorcerer")` -- Error
`spell:vocation("Sorcerer)` -- Correct because in the xml file it is written that way

Now with these changes the two options are valid

**Issues addressed:** Nothing!

2021-04-05 08:04 UTC, ranisalt requested changes
Please avoid using raw C functions, use [this pattern](https://github.com/otland/forgottenserver/blob/f2d74c67959308636a7a725de3bb5af9492b9d61/src/game.cpp#L440-L442) instead

2021-04-05 19:26 UTC, ranisalt requested changes

2021-04-05 19:26 UTC, ranisalt commented on src/vocation.cpp
> +			});
I believe the indentation is wrong here, it should be 1 level to the left

2021-04-16 23:35 UTC, DSpeichert approved these changes

2021-04-17 08:43 UTC, ranisalt approved these changes
Cool

2021-04-17 10:45 UTC, nekiro approved these changes

2021-04-17 11:51 UTC, merged