npc shop cash exploit warning
otland/forgottenserver pull request #3408
Opened 2021-04-09 00:38 UTC by idontreallywolf

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Send warning in console to warn about possible cash exploit.

**Issues addressed:** #3339 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2021-04-09 01:34 UTC, omarcopires approved these changes

2021-04-09 01:44 UTC, omarcopires commented
This is a very useful check, but it would be interesting to check between all the npcs and also show the name of the NPC in Warning.

2021-04-09 03:05 UTC, EPuncker requested changes

2021-04-09 03:05 UTC, EPuncker commented on data/npc/lib/npcsystem/modules.lua
> +					print('[NpcSystem - ShopModule::addBuyableItem] Buy price lower than sell price ('.. shopItem.name ..')')
```suggestion
					print("[Warning : " .. Npc():getName() .. "] NpcSystem: Buy price lower than sell price: (".. shopItem.name ..")")
```

2021-04-09 03:05 UTC, EPuncker commented on data/npc/lib/npcsystem/modules.lua
> +					print('[NpcSystem - ShopModule::addSellableItem] Sell price higher than buy price ('.. shopItem.name ..')')
```suggestion
					print("[Warning : " .. Npc():getName() .. "] NpcSystem: Sell price higher than buy price: (".. shopItem.name ..")")
```

2021-04-09 09:51 UTC, EPuncker approved these changes

2021-04-09 23:27 UTC, MillhioreBT approved these changes
I do not see any reason to reject these changes, it will be of great help for the modification of our servers, respect to the Npc's ;)

2021-04-10 22:48 UTC, EvilHero90 approved these changes
good addition, don't see any reason as to why we shouldn't add this.

2021-04-10 23:08 UTC, merged

2021-05-02 13:21 UTC, Dip-Set1 commented
Found small bug, items with subtypes (mugs, vials, etc) and same item id, will create false report
```
[Warning : Sandra] NpcSystem:   Found duplicated item:   vial of oil,2006,20,11
[Warning : Sandra] NpcSystem:   Found duplicated item:   vial of slime,2006,12,4
[Warning : Sandra] NpcSystem:   Found duplicated item:   vial of urine,2006,10,13
[Warning : Sandra] NpcSystem:   Found duplicated item:   vial of water,2006,8,1
```