configurable data directory
otland/forgottenserver pull request #3465
Opened 2021-05-18 13:31 UTC by rookgaard

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Have you ever had thought you wanted to name each datapack for each server you have, while having the same engine? Now, using idea from 0.X, you can!

Changes I proposed replaces all occurences of hardcoded "data/" to string loaded from config file with default value as "data/", so from perspective of regular TFS user nothing will change, but give opportunity for those who (like me), wants to rename "data" directory.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2021-05-18 13:31 UTC, rookgaard commented
@EPuncker Can you add reviewers please?

2021-05-19 21:46 UTC, MillhioreBT commented
I think that with Git we can already handle different branches of the same project and just changing branches is enough to test different data packages, at least that's how I do it

2021-05-19 21:52 UTC, rookgaard commented
> I think that with Git we can already handle different branches of the same project and just changing branches is enough to test different data packages, at least that's how I do it

That means, changes I proposed are exactly for you! :D

2021-05-19 22:42 UTC, EPuncker commented
I like this idea because right now for example I have two different servers that use the same source but different datapacks and it will fit just nicely

2021-05-20 07:31 UTC, MillhioreBT approved these changes
Just because it is a more comfortable way to do it for anyone, I accept it!

2021-05-20 12:18 UTC, ranisalt requested changes
The suggestion applies to all changes you made.

However, I suggest to pass the data folder in the command line (e.g. `tfs --data path/to/data` defaulting to `$CWD/data`)

2021-05-20 12:18 UTC, ranisalt commented on src/baseevents.cpp
> +	std::string basePath = g_config.getString(ConfigManager::DATA_DIRECTORY) + scriptsName + "/";
Please use a [`std::filesystem::path`](https://en.cppreference.com/w/cpp/filesystem/path) instead

2021-05-20 12:18 UTC, ranisalt commented on src/chat.cpp
> +	std::string chatchannelsFile = dataDirectory + "chatchannels/chatchannels.xml";
Same as above

2021-05-20 12:18 UTC, ranisalt commented on src/script.cpp
>  	namespace fs = boost::filesystem;
You can now change this to be `std::filesystem`, we used `boost` because C++11 didn't have `filesystem` but C++17 has.

2021-05-25 22:44 UTC, kornholi commented
What do you think about a `ConfigManager::getDataPath` that returns `std::filesystem::path`? Then you could use `getDataPath() / "foo.xml"` etc.

2021-06-06 06:32 UTC, DSpeichert commented
We have `data/`, `config.lua` and `key.pem`.

You'd still need to change the working directory to be able to choose different config.lua and (rarely) different key.pem.
So having "same engine", how is this better than specifying e.g. `WorkingDirectory=/path/to...` in a systemd unit?

2021-07-03 09:06 UTC, Zbizu commented
Why not go further and create a login server?

2021-09-17 23:56 UTC, DSpeichert commented
This seems abandoned after a number of thoughtful reviews, so I'm closing this. Feel free to respond or reopen.

2021-09-17 23:56 UTC, closed without merging