fix Items::getItemIdByName
otland/forgottenserver pull request #3588
Opened 2021-08-21 21:38 UTC by yamaken93

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Prevent empty names from being added to nameToItems and prevent Items::getItemByName return a valid item id when the name is empty.
Make sure the Items::getItemIdByName behavior is exact: for each item id there will be only one name and the name will be the first found in items.xml.
Changed NameMap from unordered_multimap to unordered_map since multiple keys is useless now and probably before.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2021-08-21 22:12 UTC, EPuncker approved these changes

2021-08-24 06:34 UTC, MillhioreBT commented on src/items.cpp
> +		if (result == nameToItems.end()) {
I think the temporary `result` is not necessary
`if (nameToItems.find(lowerCaseName) == nameToItems.end()) {`

2021-08-24 08:00 UTC, ranisalt requested changes

2021-08-24 08:00 UTC, ranisalt commented on src/items.cpp
> +			nameToItems.insert({ std::move(lowerCaseName), id });
```suggestion
			nameToItems.emplace(std::move(lowerCaseName), id);
```

2021-09-16 23:10 UTC, EPuncker approved these changes

2021-09-16 23:26 UTC, DSpeichert approved these changes

2021-09-17 23:54 UTC, merged