avoid -Werror=unused-function on signals
otland/forgottenserver pull request #3703
Opened 2021-09-29 14:11 UTC by Diego-OT

Avoiding compilation errors in cases where the -Werror flag is used

### Pull Request Prelude

- [ ] I have followed [proper The Forgotten Server code styling][code].
- [ ] I have read and understood the [contribution guidelines][cont] before making this PR.
- [ ] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

" error: ‘void {anonymous}::sigbreakHandler()’ defined but not used [-Werror=unused-function]"

https://prnt.sc/1u3hn16

**Issues addressed:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2021-09-29 20:43 UTC, EPuncker commented on src/signals.cpp
> +			g_dispatcher.join();
```suggestion
			g_dispatcher.join();
```

2021-09-29 22:47 UTC, ranisalt commented
Huh, why aren't they used?

2021-11-01 01:15 UTC, DSpeichert requested changes
See earlier comment.

This also clearly causes warnings.

2022-01-25 23:47 UTC, DSpeichert commented
Closing because abandoned.

2022-01-25 23:47 UTC, closed without merging