#3768 - Fixing use of  item on the house door
otland/forgottenserver pull request #3786
Opened 2021-11-13 09:48 UTC by ArturKnopik

#3768 - Fixing use of  item on the house door

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

2021-11-13 11:37 UTC, marmichalski commented
This is not only house door but also "shop-like" houses where walls are counters. Anyway, that's nitpicking, but shouldn't that feature be somehow dependant of `ONLY_INVITED_CAN_MOVE_HOUSE_ITEMS` config option? And maybe that option should be rename to something more universal? Or maybe this feature should have it's own flag. Having it enable and non-configurable is not a way to go, IMHO.

2021-11-13 11:41 UTC, marmichalski commented on src/actions.cpp
> +			player->sendCancelMessage(RETURNVALUE_NOTPOSSIBLE);
```suggestion
			player->sendCancelMessage(RETURNVALUE_PLAYERISNOTINVITED);
```

❓

2021-11-14 14:33 UTC, nekiro requested changes

2021-11-14 14:33 UTC, nekiro commented on src/actions.cpp
> +
```suggestion
if (g_config.getBoolean(ConfigManager::ONLY_INVITED_CAN_MOVE_HOUSE_ITEMS)) {
	if (HouseTile* houseTile = dynamic_cast<HouseTile*>(item->getTile())) {
		House* house = houseTile->getHouse();
		if (house && !house->isInvited(player)) {
			player->sendCancelMessage(RETURNVALUE_PLAYERISNOTINVITED);
			return false;
		}
	}
}
```

2021-11-15 01:51 UTC, EPuncker commented
tabbing seems to be off by 1 from the rest of the code, other than that, looks good

2021-11-15 11:19 UTC, nekiro commented
> tabbing seems to be off by 1 from the rest of the code, other than that, looks good

Might be, my tabbing skills in www github are bad xD

2021-11-15 13:41 UTC, ArturKnopik commented
cleaned

2021-11-15 13:42 UTC, nekiro commented on src/actions.cpp
> +	}
new line here please

2021-11-15 16:38 UTC, nekiro approved these changes

2021-11-15 17:24 UTC, EPuncker approved these changes

2021-11-15 23:10 UTC, merged