Cherry-pick: make two-factor auth optional
otland/forgottenserver pull request #3835
Opened 2021-12-05 22:28 UTC by omarcopires

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed 
Using two-factor authentication is now optional.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2021-12-05 22:46 UTC, Zbizu commented
Context behind this change: most version 12 tools use login/password sessionKey without including two more fields for token and timestamp. This causes server to refuse the connection. This change allows disabling check for these two fields from config.lua, making the server more compatible with these tools.

2021-12-06 00:06 UTC, DSpeichert requested changes
You're changing default behavior - introducing new config option with a default value opposite to the current behavior.

Also, cherry-picking refers to (typically) backporting changes from one newer code to previous, maintained branches. This is cherry-picking from... where exactly?

2021-12-06 01:12 UTC, omarcopires commented
> You're changing default behavior - introducing new config option with a default value opposite to the current behavior.
> 
> Also, cherry-picking refers to (typically) backporting changes from one newer code to previous, maintained branches. This is cherry-picking from... where exactly?

hello, the code was removed from https://github.com/Zbizu/forgottenserver/commit/07e66f7be06e5ee8c37aed1e387d705eb022d0a2

2021-12-06 01:58 UTC, Zbizu requested changes

2021-12-06 01:58 UTC, Zbizu commented on src/configmanager.cpp
> +	boolean[TWO_FACTOR_AUTH] = getGlobalBoolean(L, "enableTwoFactorAuth", false);
set here to `true` and the default behaviour will be kept

2021-12-06 02:02 UTC, Zbizu commented
> Also, cherry-picking refers to (typically) backporting changes from one newer code to previous, maintained branches. This is cherry-picking from... where exactly?

It comes from a fork that is a few features ahead of the main repo so as long as it doesn't conflict it's just as you described.

2021-12-06 15:58 UTC, EPuncker approved these changes

2021-12-15 18:09 UTC, EPuncker commented
@DSpeichert this can be accepted/merged but your request change status is blocking it

2021-12-17 08:48 UTC, nekiro approved these changes

2021-12-17 08:50 UTC, Zbizu approved these changes

2021-12-18 18:39 UTC, EPuncker approved these changes

2021-12-18 18:39 UTC, merged