feat: special magic level
otland/forgottenserver pull request #3843
Opened 2021-12-12 15:07 UTC by ArturKnopik

16:06 You see a rainbow shield (Def:30, energy magic level +20, fire magic level +3, healing magic level +10).
It can only be wielded properly by knights of level 100 or higher.
It weighs 69.00 oz.
Strange elemental magic flows over this shield.
![specialSkillMlvl](https://user-images.githubusercontent.com/17506599/145717794-5ce6149f-a01e-435a-82dc-204dbb75fb76.png)

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:**

2021-12-12 17:28 UTC, Zbizu commented
I believe that they should also be pushed to lua (in itemType:getAbilities())

2021-12-12 18:54 UTC, EPuncker commented on src/items.h
> +	std::array<int16_t, COMBAT_COUNT> specialMagicLevelSkill = { 0 };
```suggestion
	std::array<int16_t, COMBAT_COUNT> specialMagicLevelSkill = {0};
```

2021-12-12 18:54 UTC, EPuncker commented on src/player.h
> +		std::array<int16_t, COMBAT_COUNT> specialMagicLevelSkill = { 0 };
```suggestion
		std::array<int16_t, COMBAT_COUNT> specialMagicLevelSkill = {0};
```

2021-12-13 19:06 UTC, EPuncker requested changes

2021-12-13 19:06 UTC, EPuncker commented on src/item.cpp
> +						else {
`} else {` same with others, other than that, this PR is ready to be merged

2021-12-14 01:25 UTC, omarcopires commented on src/protocolgame.cpp
> +			else {
code style

2021-12-14 01:25 UTC, omarcopires commented on src/item.cpp
> +					else {
code style

2021-12-14 01:25 UTC, omarcopires commented on src/item.cpp
> +						else {
code style

2021-12-14 01:25 UTC, omarcopires commented on src/item.cpp
> +					else {
code style

2021-12-14 01:25 UTC, omarcopires commented on src/item.cpp
> +						else {
code style

2021-12-14 09:30 UTC, nekiro commented
What healing magic level stands for? It boosts magic level or the formula that decides how much you heal from magic level?

2021-12-14 17:39 UTC, ArturKnopik commented on src/item.cpp
> +					else {
fixed

2021-12-14 17:39 UTC, ArturKnopik commented on src/item.cpp
> +						else {
fixed

2021-12-14 17:39 UTC, ArturKnopik commented on src/item.cpp
> +					else {
fixed

2021-12-14 17:42 UTC, ArturKnopik commented on src/item.cpp
> +					else {
fixed

2021-12-14 17:42 UTC, ArturKnopik commented on src/item.cpp
> +						else {
fixed

2021-12-14 17:42 UTC, ArturKnopik commented on src/protocolgame.cpp
> +			else {
fixed

2021-12-14 18:42 UTC, EPuncker approved these changes
tested and working :)

2021-12-14 18:46 UTC, merged

2021-12-21 19:25 UTC, omarcopires commented
This feature ends a task from issue #3758
`New types of items modifiers were be implemented: Specialised Magic Levels, Cleave, Magic Shield Capacity, Perfect Shot (aka Range Bonus), Damage Reflection [12.70.10953]`