Fix skill status when item decays
otland/forgottenserver pull request #3851
Opened 2021-12-15 15:23 UTC by Diego-OT

Steps to reproduce the bug:

Equip an item that give you some bonus skill and decay to another item or 0.
When it decay, you will continue with that bonus.

part of fix:
https://github.com/opentibiabr/canary/blob/77e037dd72063279754e6efa8ae97a5843981111/src/game/game.cpp#L6474

full fix:
checks if the item is being carried by the player and also check if the item is equipped to avoid skill changes when the item decay inside backpack (not equipped).

2021-12-18 10:40 UTC, Znote commented on src/player.cpp
> +		if (checkitem and (checkitem == item)) {
```suggestion
		if (checkitem && (checkitem == item)) {
```

2024-05-26 00:59 UTC, Codinablack requested changes
Looks good overall. The changes I requested are nothing serious, just reducing code duplication. Fix those and I will approve.

2024-05-26 00:59 UTC, Codinablack commented on src/game.cpp
> +			if (needUpdateSkills) {
This update here is an un-needed duplicate. You already update at the end where it should be.

2024-05-26 00:59 UTC, Codinablack commented on src/player.cpp
> +bool Player::isEquippedItem(const Item* item) const
For this function, TFS already has a way of checking if an item is one of those slots, Player::getInventoryItem. Utilize that method for this one.

2024-05-26 09:46 UTC, ranisalt commented
@Codinablack fixed your suggestions and rebased to fix conflicts

2024-06-03 07:11 UTC, Codinablack approved these changes
Looks good to me!

2024-06-03 07:44 UTC, Codinablack commented
> Looks good to me!

I stand corrected. This fix looks like it would serve as a good fix, if skill status didn't already change during decay by calling postRemoveNotification, because of that, this PR isn't necessary.

2024-06-03 07:49 UTC, nekiro commented
Stats/skills are properly updated for decaying items (they get called from postRemoveNotification)

2024-06-03 07:49 UTC, closed without merging