Added Podium feature
otland/forgottenserver pull request #3858
Opened 2021-12-17 02:15 UTC by EPuncker

Co-Authored-By: Zbizu <Zbizu@users.noreply.github.com>

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Added podium feature (item ids: 38629-38630), fully working except the outfit and mount name on description.
![2021-12-16 23_10_52-Tibia - Perflex](https://user-images.githubusercontent.com/4684880/146477759-85a701e3-1726-4e3c-a4b4-969f569e3fc9.png)

credit: @Zbizu 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2021-12-17 05:18 UTC, Zbizu commented
The podiums can be set from rme btw:
https://github.com/Zbizu/rme

Don't forget to build me an altar :P

2022-02-06 06:32 UTC, DSpeichert approved these changes

2022-02-06 14:55 UTC, EPuncker commented on src/luascript.cpp
> +	else {
```suggestion
	} else {
```

2022-02-06 14:55 UTC, EPuncker commented on src/luascript.cpp
> +	}
```suggestion
```

2022-02-06 16:39 UTC, nekiro requested changes

2022-02-06 16:39 UTC, nekiro commented on src/game.cpp
> +void Game::updatePodium(Item* item) {
{ in new line

2022-02-06 16:39 UTC, nekiro commented on src/item.h
> +			return it.isPodium();
one liner? items[id].isPodium()

2022-02-06 16:39 UTC, nekiro commented on src/podium.cpp
> +	switch (attr) {
tabbing is off or is it github showing is bad?

2022-02-06 16:39 UTC, nekiro commented on src/podium.h
> +			return (this->flags & flag) != 0;
use bitset for flags, everywhere

2022-02-06 16:39 UTC, nekiro commented on src/protocolgame.cpp
> +		return;
tabs seem off again, github or broken tabs?

2022-02-14 22:18 UTC, DSpeichert commented on src/podium.h
> +			return (this->flags & flag) != 0;
What about this @EPuncker ?

2022-02-18 22:12 UTC, DSpeichert commented on src/events.cpp
> +	// Player:onPodiumEdit(item, outfit, direction, isVisible) or Player.onPodiumEdit(self, item, outfit, direction, isVisible)
```suggestion
	// Player:onPodiumEdit(item, outfit, direction, isVisible)
	// Player.onPodiumEdit(self, item, outfit, direction, isVisible)
```

2022-02-18 22:12 UTC, DSpeichert submitted a review, later dismissed

2022-02-19 00:53 UTC, merged