Small update to channel requirements
otland/forgottenserver pull request #3859
Opened 2021-12-17 03:04 UTC by EPuncker

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- added onJoin message to both advertising channels
- removed level check from rook-advertising
- changed level from 1 to 20 and added premium requirement to bypass it
- updated message accordingly

yes these changes are based on cipbia but I added them because they make sense, not to mimic or something

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2021-12-21 01:25 UTC, DSpeichert requested changes
Are you sure? x3

2021-12-21 01:25 UTC, DSpeichert commented on data/chatchannels/scripts/advertising.lua
> +	if player:getLevel() < 20 or not player:isPremium() then
```suggestion
	if player:getLevel() < 20 and not player:isPremium() then
```
That logic seems to be not what was intended.

2022-01-18 13:26 UTC, omarcopires commented
This is the actual behavior of channels, everything looks right, there is no reason not to add it.

2022-01-18 13:26 UTC, omarcopires approved these changes

2022-01-24 01:14 UTC, DSpeichert approved these changes

2022-01-24 01:14 UTC, merged