Added VipGroups (11.10)
otland/forgottenserver pull request #3879
Opened 2022-01-02 05:25 UTC by reyaleman

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Added vipgroups functionality. (v11.10)

![01](https://user-images.githubusercontent.com/3027705/147867062-b562ac96-606e-472a-8944-911aa88322a9.PNG)
![02](https://user-images.githubusercontent.com/3027705/147867064-6ca5ab67-0633-4772-973f-5424314607a5.PNG)

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2022-01-02 17:34 UTC, EPuncker requested changes
and please add the schema changes to schema.sql too

2022-01-02 17:34 UTC, EPuncker commented on src/configmanager.cpp
> +	integer[VIPGROUP_FREE_LIMIT] = getGlobalNumber(L, "vipGroupFreeLimit", 3);
use same default values as config.lua file

2022-01-02 17:34 UTC, EPuncker commented on src/luascript.cpp
> +	else {
```suggestion
	} else {
```

2022-01-02 17:34 UTC, EPuncker commented on src/luascript.cpp
> +	}
```suggestion
```

2022-02-14 01:05 UTC, DSpeichert requested changes

2022-02-14 01:05 UTC, DSpeichert commented on data/migrations/32.lua
> +	db.query("ALTER TABLE `account_viplist` RENAME `account_vipentries`")
I'd leave that as-is for backwards compatibility.

2022-02-14 01:05 UTC, DSpeichert commented on data/migrations/32.lua
> +	print("END //")
Why not run that in migration?

2022-02-14 01:05 UTC, DSpeichert commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `vipgroup_vipentry` (
`account_vipgroup_entry` is a better name, it would list lexically right next to `account_vipgroups`

2022-02-15 21:50 UTC, ranisalt requested changes

2022-02-15 21:50 UTC, ranisalt commented on src/iologindata.cpp
> +std::forward_list<VIPGroup> IOLoginData::getVIPGroups(uint32_t accountId)
Use a vector here, no need to use a forward list which wastes memory

2022-04-29 14:41 UTC, LukSrT requested changes

2022-04-29 15:27 UTC, ranisalt commented
Is someone willing to revive this PR? Apart from the comments, it should also use const& vectors to avoid copies, and needs to be reformated.

2022-05-18 05:39 UTC, reyaleman commented
> Is someone willing to revive this PR? Apart from the comments, it should also use const& vectors to avoid copies, and needs to be reformated.

It's ok if I close this pull request and open a new one with the changes requested? I tried to rebase this but failed 😂

2022-05-18 11:50 UTC, ranisalt commented
> It's ok if I close this pull request and open a new one with the changes requested? I tried to rebase this but failed 😂

Go ahead!

2022-05-18 13:29 UTC, closed without merging