1.4.2 Release Candidate
otland/forgottenserver pull request #3917
Opened 2022-01-30 04:15 UTC by Znote

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Cherry-picking bugfixes into 1.4.1 from master to make 1.4.2

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2022-01-30 04:42 UTC, Znote commented
I want to wait for #3915 to get merged to master, and probably cherry-pick it here. So no need to submit approval reviews here yet.
This list of bugfixes was sent to me by @EPuncker, if there is anything I have missed that should go into 1.4.2, please let me know.

2022-01-30 09:45 UTC, EPuncker requested changes

2022-01-30 09:45 UTC, EPuncker commented on data/lib/core/player.lua
> +function Player.updateKillTracker(self, monster, corpse)
this need to be removed

2022-02-24 01:06 UTC, EPuncker requested changes
just a minor request change and I think its ready

2022-02-24 01:06 UTC, EPuncker commented on src/luascript.h
> +#include "mounts.h"
```suggestion
```

2022-02-24 01:11 UTC, EPuncker approved these changes

2022-05-08 19:01 UTC, Codinablack commented
I have been using this branch to develop on for more than a couple months now, for so long that I was confident enough, it was stable enough, for me to build on top of it, my own server. So I am just saying, this is a great candidate for 1.4.2 I had zero problems with it during its use.

2022-05-08 19:02 UTC, Codinablack approved these changes

2022-05-09 00:26 UTC, DSpeichert approved these changes

2022-05-09 00:27 UTC, merged