rsa: tolerate whitespaces better
otland/forgottenserver pull request #3940
Opened 2022-02-14 23:15 UTC by DSpeichert

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

* Find PEM header and footer in `key.pem` instead of assuming it is exactly the entirety of the file.
* Color startup errors with fmt

See: https://cryptopp.com/wiki/Keys_and_Formats#PEM_Encoded_Keys

2022-02-14 23:23 UTC, EPuncker commented on src/rsa.cpp
> +	if(pos1 == std::string::npos) {
```suggestion
	if (pos1 == std::string::npos) {
```

2022-02-16 19:41 UTC, ranisalt requested changes

2022-02-16 19:41 UTC, ranisalt commented on src/rsa.cpp
> +		throw std::runtime_error("Missing RSA private key PEM footer.");
`pos1` and `pos2` could be `headerIndex` and `footerIndex`

2022-02-16 23:54 UTC, ranisalt approved these changes

2022-02-17 02:11 UTC, merged