Replace virtual functions with static_cast
otland/forgottenserver pull request #4060
Opened 2022-04-02 14:08 UTC by ramon-bernardo

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- Change for static_cast on conversion is guaranteed.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2022-04-02 14:09 UTC, ramon-bernardo commented on src/monster.cpp
> -		}
This is not necessary because `getSpectators - onlyPlayers` is true

2022-04-02 21:39 UTC, ranisalt requested changes

2022-04-02 21:39 UTC, ranisalt commented on src/condition.cpp
> +						static_cast<Player*>(spectator)->sendTextMessage(message);
Please add `assert(dynamic_cast<Player*>(spectator) != nullptr)` before so we catch bugs on debug builds

2022-04-02 23:22 UTC, ranisalt commented on src/monster.cpp
> +		if ((creature->getPlayer() && !static_cast<const Player*>(creature)->hasFlag(PlayerFlag_IgnoredByMonsters)) ||
I think this is better:
```suggestion
		if (Player* player = creature->getPlayer(); player && !player->hasFlag(PlayerFlag_IgnoredByMonsters)) ||
```

2022-04-16 19:11 UTC, ranisalt commented
You'll need to rebase and reformat the files

2022-04-16 21:40 UTC, Zbizu commented
what is the context for this change? performance gain? resolving potential crashes? code cleanup?

2022-04-17 21:24 UTC, ranisalt commented
> what is the context for this pull request? performance gain? resolving potential crashes? code cleanup?

It saves one virtual function call - which cannot be inlined because the function address cannot be determined in compile time, while `static_cast` is free - when we are sure that the conversion is valid.

2022-05-17 23:04 UTC, DSpeichert commented
Is this alive? Rebase needed.

2022-05-19 22:35 UTC, ramon-bernardo reviewed
This needs attention

2022-05-19 22:35 UTC, ramon-bernardo commented on src/game.cpp
> +	const Position& mapFromPos = static_cast<Tile*>(fromCylinder)->getPosition();
Review

2022-05-19 22:35 UTC, ramon-bernardo commented on src/player.cpp
> +			requireListUpdate = static_cast<const Container*>(i)->getHoldingPlayer() != this;
Review

2022-05-19 22:35 UTC, ramon-bernardo commented on src/player.cpp
> +			requireListUpdate = static_cast<const Container*>(i)->getHoldingPlayer() != this;
Review

2022-05-19 22:52 UTC, ramon-bernardo commented
The name of last commit is "Rename tmpPlayer to spectatorPlayer".
VSCode driving me crazy. 🤪

2022-11-02 00:21 UTC, EPuncker approved these changes

2022-11-10 20:55 UTC, ranisalt approved these changes

2022-11-10 20:56 UTC, merged

2022-11-15 13:53 UTC, conde2 commented
> > what is the context for this pull request? performance gain? resolving potential crashes? code cleanup?
> 
> It saves one virtual function call - which cannot be inlined because the function address cannot be determined in compile time, while `static_cast` is free - when we are sure that the conversion is valid.

@ranisalt 
But don't we need to call the dynamic_cast now? So instead of calling the virtual getPlayer we are calling the dynamic cast. Is this tradeoff worthy?