Adding cobra monsters and their features
otland/forgottenserver pull request #4091
Opened 2022-04-24 17:34 UTC by omarcopires

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed 
* Adding common cobra bastion monsters and their spells.
* Add functionality to use cobra bastion cauldron

Credits to creators:
Co-Authored-By: Evil Puncker <EPuncker@users.noreply.github.com>
Co-Authored-By: torresmon <70948057+torresmon@users.noreply.github.com>
Co-Authored-By: Lucas Giovanni <23272175+lucasgiovannibr@users.noreply.github.com>
Co-Authored-By: Marcos <66353315+marcosvf132@users.noreply.github.com>

Content taken from: https://github.com/Epuncker/orts2

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2022-04-25 20:54 UTC, EPuncker approved these changes

2022-04-25 22:21 UTC, Zbizu requested changes

2022-04-25 22:21 UTC, Zbizu commented on data/global.lua
> +	19991, 20275, 20284, 22816, 22825, 25285, 25292, 33432, 33433
does not belong in this PR I presume

2022-04-25 22:21 UTC, Zbizu commented on data/movements/movements.xml
> +	<movevent event="StepIn" itemid="34322" script="quest_door.lua" />
same

2022-05-01 22:14 UTC, EPuncker approved these changes

2022-05-01 22:15 UTC, merged