Spells update
otland/forgottenserver pull request #4095
Opened 2022-04-26 19:36 UTC by EPuncker

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- Updated wand of darkness item stats
- Added Conjure Wand of Darkness spell
- Removed Enchant Staff spell (deprecated and replaced by the above spell)
- Fixed mana cost for the Challenge spell
- The druid spells Terra Wave and Heal Friend had their mana cost reduced from 210 and 140 to 170 and 120, respectively.
- Spell Heal Friend can't be used to heal its own caster anymore.
- Reduced distance skill bonus of Sharpshooter (utito tempo san) from 50% to 40%.
- Added Nature's Embrace spell
- Added Fair Wound Cleansing spell
- Added Restoration spell
- Added Great Fire Wave spell

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2022-04-26 19:37 UTC, EPuncker commented
Draft because still missing correct spellids or this is going to happen:

![2022-04-26 15_29_39-Tibia - Perflex](https://user-images.githubusercontent.com/4684880/165378718-a1d62435-4ec8-401c-a480-3d95c97de146.png)

2022-04-27 12:28 UTC, ranisalt requested changes

2022-04-27 12:28 UTC, ranisalt commented on data/items/items.xml
> +		<attribute key="decayTo" value="0" />
Either write every key in lowercase or in camel case

2022-04-27 15:41 UTC, ranisalt approved these changes
LGTM

2022-04-27 15:45 UTC, merged