Better Handling Of Depot Chest And Lockers
otland/forgottenserver pull request #4234
Opened 2022-10-29 01:46 UTC by ramon-bernardo

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

#### PR BASE #3698

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2022-10-31 00:17 UTC, EPuncker submitted a review, later dismissed

2022-11-02 01:11 UTC, ramon-bernardo commented on src/depotchest.h
> +	void setOwner(Player* owner) { this->owner = owner; }
Its not necess

2022-11-10 11:44 UTC, nekiro commented on src/player.cpp
> +	it->second->setDepotId(depotId);
what about moving this to constructor?

2022-11-10 22:05 UTC, ramon-bernardo commented on src/player.cpp
> +	it->second->setDepotId(depotId);
Thanks!

2022-11-10 22:28 UTC, ranisalt requested changes

2022-11-10 22:28 UTC, ranisalt commented on src/depotchest.cpp
> +    Container{type, items[type].maxItems, true, paginated}, depotId(depotId)
```suggestion
    Container{type, items[type].maxItems, true, paginated}, depotId{depotId}
```

2022-12-05 21:42 UTC, closed without merging