Add Player.addBankMoney function
otland/forgottenserver pull request #4318
Opened 2023-02-08 03:57 UTC by omarcopires

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed 
Description:

The function Player.addBankMoney adds a specified amount of money to the player's bank balance. The function takes two parameters: self and amount. The self parameter refers to the player object calling the function and the amount parameter is the amount of money to be added to the player's bank balance.

The function starts by using the setBankBalance method of the player object to set the player's bank balance to the current balance plus the specified amount. This will update the player's bank balance with the added amount.

Example usage:
```lua
player:addBankMoney(100)
```
The addBankMoney function is then called on this player object, with the parameter 100, to add 100 gold coins to the player's bank balance.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2023-02-08 04:16 UTC, EPuncker submitted a review, later dismissed

2023-02-08 09:59 UTC, ranisalt requested changes

2023-02-08 09:59 UTC, ranisalt commented on data/lib/core/player.lua
> +function Player.addBankMoney(self, amount)
Keep the pattern and name it `addBankBalance`
```suggestion
function Player.addBankBalance(self, amount)
```

2023-02-08 11:21 UTC, ranisalt approved these changes

2023-02-09 20:22 UTC, Zbizu approved these changes

2023-02-15 09:04 UTC, merged