Extract get killer method in Player:onDeath
otland/forgottenserver pull request #4427
Opened 2023-04-27 13:59 UTC by ranisalt

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 
Doing some cleanup in this file, I noticed there was duplication when checking if the killer/most damage attacker were players. Extracting to a function allowed reusing the code and making it simpler, with less indentation levels and temporary values.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2023-04-27 15:26 UTC, EPuncker submitted a review, later dismissed

2023-04-27 23:39 UTC, MillhioreBT requested changes

2023-04-27 23:39 UTC, MillhioreBT commented on data/creaturescripts/scripts/player_death.lua
> +local function getKiller()
missing arg

2023-04-28 09:00 UTC, ranisalt commented on data/creaturescripts/scripts/player_death.lua
> +local function getKiller()
Indeed, not sure how it ran 🤔 fixed

2023-04-28 15:52 UTC, MillhioreBT approved these changes
LGTM

2023-04-28 16:01 UTC, EPuncker approved these changes

2023-04-29 10:40 UTC, merged