Add storage values to creatures
otland/forgottenserver pull request #4495
Opened 2023-06-27 21:57 UTC by ranisalt

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:**
Moves storage values up from players to creatures, meaning that monsters and NPCs also get storage values. 

Only player storage is saved to the database, since creatures are not stable between server restarts. It could be extended to save NPC storage values, though.

Implementation detail: I opted for an ordered map instead of unordered because `std::unordered_map` uses a lot of memory when empty, as it is optimized for high usage.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2023-06-28 01:29 UTC, EPuncker approved these changes

2023-06-28 18:56 UTC, MillhioreBT commented
I think the change is beautiful and necessary, however it must be taken into account that all otland scripts will break.
because now -1 is replaced by nil

2023-06-28 19:19 UTC, omarcopires commented
> I think the change is beautiful and necessary, however it must be taken into account that all otland scripts will break.
> 
> because now -1 is replaced by nil

maybe it's something very stupid, but just adding to compat wouldn't be enough?

2023-06-28 19:28 UTC, MillhioreBT commented
> > I think the change is beautiful and necessary, however it must be taken into account that all otland scripts will break.
> > because now -1 is replaced by nil
> 
> maybe it's something very stupid, but just adding to compat wouldn't be enough?

sure, this is probably the way to go.

2023-06-28 19:35 UTC, EPuncker requested changes
why nil instead of -1? 🤔

2023-06-29 10:05 UTC, ranisalt commented
> why nil instead of -1? 🤔

Trying to sneakily fix this prehistoric fuck up

2023-06-30 18:38 UTC, MillhioreBT commented
> > why nil instead of -1? 🤔
> 
> Trying to sneakily fix this prehistoric fuck up

Add compatibility functions in compat.lua and you are good to ready 😊

2023-07-07 16:54 UTC, EPuncker approved these changes

2023-07-08 18:46 UTC, ranisalt commented
> Add compatibility functions in compat.lua and you are good to ready blush

I think the way I did it covers everything

2023-07-08 20:12 UTC, EPuncker approved these changes

2023-07-08 22:52 UTC, EPuncker approved these changes
neat

2023-07-09 14:57 UTC, merged