fix: depotchest memory leak
otland/forgottenserver pull request #4510
Opened 2023-07-23 19:50 UTC by lyuz1n

### Pull Request Prelude

- [ ] I have followed [proper The Forgotten Server code styling][code].
- [ ] I have read and understood the [contribution guidelines][cont] before making this PR.
- [ ] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

items on depot cannot destroy after player logout.
after some relogins with around 100k items on depot...

BEFORE FIX:
![Captura de tela 2023-07-23 164438](https://github.com/otland/forgottenserver/assets/40324910/572e80eb-b819-46f2-b78c-79093705e03e)

AFTER FIX:
![Captura de tela 2023-07-23 164420](https://github.com/otland/forgottenserver/assets/40324910/25957507-8466-4ede-912b-ecec38fe0fab)

`the power of the smart pointer!`

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2023-07-23 21:45 UTC, nekiro commented
https://github.com/otland/forgottenserver/pull/3423
https://github.com/otland/forgottenserver/pull/3452

2023-07-24 16:35 UTC, ranisalt commented on src/player.h
> +using DepotChest_ptr = std::shared_ptr<DepotChest>;
Just use `std::shared_ptr<DepotChest>` directly

2023-07-28 13:17 UTC, moviebr approved these changes
Nice :)

2023-07-29 11:06 UTC, nekiro requested changes
This will crash, because of double pointer deletion, one happens from container destructor, because depot is a regular item inside locker (you have to remove depot from locker on player destructor to avoid that) and the second will trigger from shared_ptr trying to delete assigned object

2023-08-15 14:17 UTC, ranisalt commented
@nekiro is right, if you're going to change to a shared ptr, you must change it _everywhere_ or you will get nasty double frees

2024-10-30 01:56 UTC, ramon-bernardo commented
I ran some tests, and it seems that the code below solves this issue 👇🏻 
```c++
Player::~Player()
{
	for (auto [_, depotChest] : depotChests) {
		delete depotChest;
	}
}

2024-12-22 22:10 UTC, nekiro commented
superseded by #4879

2024-12-22 22:10 UTC, closed without merging