Enable unity build to speed up compilation
otland/forgottenserver pull request #4545
Opened 2023-10-01 11:56 UTC by ranisalt

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Unity build will batch several files to be compiled at once (as if they were `#include`d into one), which leads to faster builds by reducing the number of times header files are processed.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2023-10-01 17:11 UTC, EPuncker approved these changes

2023-10-07 01:36 UTC, MillhioreBT approved these changes
I don't know why the unit test failed, but this really makes it compile faster.

2023-10-07 05:16 UTC, EPuncker submitted a review, later dismissed

2023-11-09 16:40 UTC, beats-dh approved these changes

2023-11-09 19:16 UTC, nekiro submitted a review, later dismissed

2023-11-13 03:07 UTC, Zbizu requested changes
can be enabled in Windows also by adding this to `.vcxproj`
tested on most recent master branch (a904904) and it compiles
```patch
diff --git a/vc17/theforgottenserver.vcxproj b/vc17/theforgottenserver.vcxproj
index 0d040e59..4798b457 100644
--- a/vc17/theforgottenserver.vcxproj
+++ b/vc17/theforgottenserver.vcxproj
@@ -39,11 +39,13 @@
     <ConfigurationType>Application</ConfigurationType>
     <UseDebugLibraries>false</UseDebugLibraries>
     <PlatformToolset>v143</PlatformToolset>
+       <EnableUnitySupport>true</EnableUnitySupport>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
     <ConfigurationType>Application</ConfigurationType>
     <UseDebugLibraries>false</UseDebugLibraries>
     <PlatformToolset>v143</PlatformToolset>
+       <EnableUnitySupport>true</EnableUnitySupport>
   </PropertyGroup>
   <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
   <ImportGroup Label="ExtensionSettings">
```

2023-12-10 01:22 UTC, EPuncker submitted a review, later dismissed

2023-12-10 12:31 UTC, EPuncker approved these changes

2023-12-13 00:56 UTC, merged