refactor: replace -1 with nil
otland/forgottenserver pull request #4578
Opened 2023-12-01 17:09 UTC by omarcopires

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed 
This commit refactors the code to replace occurrences of the value -1 with nil. The use of nil provides clearer semantics and improves code readability. The change ensures consistency and enhances the overall quality of the codebase.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2023-12-02 02:26 UTC, Zbizu commented
this change introduces `nil` comparisons which tfs moved away from, except for situations when both nil and false can be returned by a function and need to be distinguished

if the statement does not need to distinguish between false and nil:
- `~= nil` is not necessary in logical statements
- `if x == nil then` should be replaced with `if not x then`

2023-12-02 03:07 UTC, MillhioreBT commented
What @Zbizu says is true, please make the change from `if not x then`
and for cases of setStorageValue(-1), change to removeStorageValue

2023-12-04 17:06 UTC, MillhioreBT commented on data/creaturescripts/scripts/login.lua
> +	if player:isPremium() and player:getStorageValue(PlayerStorageKeys.promotion) == 1 then
The value here can be null, leave it as it was, just add `value and value == 1`

2023-12-04 17:09 UTC, MillhioreBT requested changes
Change what you check on line 16 in login.lua

2023-12-04 19:59 UTC, merged