Map protocol codes
otland/forgottenserver pull request #4581
Opened 2023-12-09 02:42 UTC by ramon-bernardo

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- Maps all packet codes between client-server.

Thanks otclient.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2023-12-09 02:45 UTC, EPuncker commented on src/CMakeLists.txt
> +    ${CMAKE_CURRENT_LIST_DIR}/protocolcodes.h
```suggestion
	${CMAKE_CURRENT_LIST_DIR}/protocolcodes.h
```

2023-12-09 02:46 UTC, ramon-bernardo commented on src/protocolgame.cpp
> +	msg.addByte(GAME_SERVER_SEND_CLIENT_CHECK);
Otclient does not handle the rest of this packet.
it seems to me that this rest is `GAME_SERVER_SEND_CLIENT_CHECK`.

We don't have a turn packet at otclient 😞

2023-12-09 02:47 UTC, EPuncker commented on src/protocolcodes.h
> +	// original tibia ONLY
```suggestion
	// official client ONLY
```

2023-12-09 02:47 UTC, EPuncker commented on src/protocolcodes.h
> +	// original tibia ONLY
```suggestion
	// official client ONLY
```

2023-12-09 02:55 UTC, ramon-bernardo commented on src/protocolcodes.h
> +	GAME_SERVER_RULE_VIOLATION_LOCK = 177,
Violations need to be mapped?

`GAME_SERVER_EXPERIENCE_TRACKER` = `GAME_SERVER_RULE_VIOLATION_REMOVE`

2024-03-27 09:14 UTC, Zbizu requested changes

2024-04-01 00:26 UTC, closed without merging

2024-04-01 01:53 UTC, luanluciano93 commented
@ramon-bernardo Can you share your discord?

2025-11-19 11:57 UTC, luanluciano93 commented
@ramon-bernardo It's a good time to reopen this, my friend.

2025-11-19 12:01 UTC, ramon-bernardo commented
@luanluciano93 Im rewriting the connection and protocol, so we won't need this anymore 😄 (https://github.com/ramon-bernardo/fork-forgottenserver-otland/pull/1).

But first, we want to merge the smart pointer things