Game state changes
otland/forgottenserver pull request #4662
Opened 2024-04-28 20:22 UTC by ramon-bernardo

### Pull Request Prelude
- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- Use generic to get game state.
- Avoid `Game.GameState` redundancy

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2024-04-28 20:37 UTC, MillhioreBT requested changes

2024-04-28 20:37 UTC, MillhioreBT commented on src/game.h
> +	template <GameState_t S>
there is no point in using a template in this case, we should avoid that if not necessary

2024-04-28 20:39 UTC, MillhioreBT commented on src/game.h
> +	template <GameState_t S>
just use a classic argument of type GameState_t and that's it, why add so much magic for a simple return int == int;

2024-04-29 12:08 UTC, EPuncker approved these changes

2024-04-29 12:12 UTC, ranisalt commented on data/lib/compat/compat.lua
> +	return Game.inState(state)
```suggestion
	return Game.getState() == state
```

Drop that C++ thingy

2024-04-29 12:14 UTC, ranisalt commented on src/game.h
> +	}
Same, you can drop it and move the definition of `getState` to the header so it gets inlined (likely gets inlined anyway with LTO)

2024-05-01 08:44 UTC, nekiro commented
What's the benefit from this change? I fail to find one, looks purely cosmetical

2024-05-01 14:10 UTC, ramon-bernardo commented
> What's the benefit from this change? I fail to find one, looks purely cosmetical and irrelevant

Yeah, i like cosmetical code

2024-05-03 00:32 UTC, closed without merging