Minimal HTTP login server
otland/forgottenserver pull request #4706
Opened 2024-05-26 18:53 UTC by ranisalt

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

We need to provide a HTTP login server in order to allow connections from recent client versions. HTTP login can (and most likely should) be provided by an AAC that already provides other HTTP services such as a website and an API, but for simple servers we can embed a minimal login server so that a server can be fully started without external tools.

Related work:
- #2010
- #3942 (same as above, but rebased)
- [nekiro/OT12LoginServer](https://github.com/nekiro/OT12LoginServer/tree/a0f1790f31f3abb12492fe71eee7ff8e0ccdce9c) (external login server in Python)

Opposite to the two linked pull requests, this **only** provides a minimal login server and players online endpoint. There are no Lua handlers or support for any other routes, which should be responded by the AAC - news, event calendar, and possibly others.

In the future, when boosted creature/boss are implemented, we can also modify the HTTP server to respond to these routes.

**This pull request must be merged after #4675 otherwise it is too massive!**
Merging it as is will also close #4661 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2024-05-27 20:54 UTC, ranisalt commented
Somehow I removed _the http server_ when rebasing

2024-05-31 02:15 UTC, EvilHero90 requested changes

2024-05-31 02:15 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +	    "INSERT INTO `accounts` (`name`, `email`, `password`) VALUES ('', 'foo@example.com', SHA1('bar'))"));
```suggestion
	    "INSERT INTO `accounts` (`name`, `email`, `password`) VALUES ('abc', 'foo@example.com', SHA1('bar'))"));
```

2024-05-31 02:15 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +	    "INSERT INTO `accounts` (`name`, `email`, `password`, `secret`) VALUES ('', 'foo@example.com', SHA1('bar'), UNHEX('48656c6c6f21dead'))"));
```suggestion
	    "INSERT INTO `accounts` (`name`, `email`, `password`, `secret`) VALUES ('abcd', 'foo@example.com', SHA1('bar'), UNHEX('48656c6c6f21dead'))"));
```

2024-05-31 02:15 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +	    "INSERT INTO `accounts` (`name`, `email`, `password`) VALUES ('', 'foo@example.com', SHA1('bar'))"));
```suggestion
	    "INSERT INTO `accounts` (`name`, `email`, `password`) VALUES ('defg', 'foo@example.com', SHA1('bar'))"));
```

2024-05-31 02:15 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +	    "INSERT INTO `accounts` (`name`, `email`, `password`, `premium_ends_at`) VALUES ('', 'foo@example.com', SHA1('bar'), {:d}) RETURNING `id`",
```suggestion
	    "INSERT INTO `accounts` (`name`, `email`, `password`, `premium_ends_at`) VALUES ('ghij', 'foo@example.com', SHA1('bar'), {:d}) RETURNING `id`",
```

2024-05-31 02:15 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +	    "INSERT INTO `accounts` (`name`, `email`, `password`, `secret`) VALUES ('', 'foo@example.com', SHA1('bar'), UNHEX('')) RETURNING `id`");
```suggestion
	    "INSERT INTO `accounts` (`name`, `email`, `password`, `secret`) VALUES ('nbdj', 'foo@example.com', SHA1('bar'), UNHEX('')) RETURNING `id`");
```

2024-05-31 02:33 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +}
```suggestion
BOOST_FIXTURE_TEST_CASE(test_login_success_no_players, LoginFixture)
{
	BOOST_TEST(db.executeQuery(
	    "INSERT INTO `accounts` (`name`, `email`, `password`) VALUES ('defg', 'foobar@example.com', SHA1('bar'))"));

	auto&& [status, body] =
	    tfs::http::handle_login({{"type", "login"}, {"email", "foobar@example.com"}, {"password", "bar"}}, ip);

	BOOST_TEST(status == status::ok);
	auto& characters = body.at("playdata").at("characters").as_array();
	BOOST_TEST(characters.size() == 0);
}
```

2024-05-31 02:33 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +}
need to create a new account here because you already added 3 chars to this test account, thus the check will always fail

2024-05-31 03:01 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +	BOOST_TEST(characters[0].at("name").as_string() == "Dejairzin");
```suggestion
	BOOST_TEST(characters[0].at("name").as_string() == "Test");
```

2024-05-31 04:03 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +	    tfs::http::handle_login({{"type", "login"}, {"email", k@example.com"}, {"password", "bar"}}, ip);
```suggestion
	    tfs::http::handle_login({{"type", "login"}, {"email", "k@example.com"}, {"password", "bar"}}, ip);
```

2024-05-31 04:08 UTC, EvilHero90 commented on src/http/tests/test_login.cpp
> +	        {"password", "bar"},
```suggestion
	    "INSERT INTO `accounts` (`name`, `email`, `password`, `secret`) VALUES ('abcd', 'fooba@example.com', SHA1('bar'), UNHEX('48656c6c6f21dead'))"));

	auto now = duration_cast<seconds>(system_clock::now().time_since_epoch());

	auto&& [status, body] = tfs::http::handle_login(
	    {
	        {"type", "login"},
	        {"email", "fooba@example.com"},
	        {"password", "bar"},
```

2024-05-31 04:13 UTC, EvilHero90 approved these changes
sorry for the 1000 commits but tests are fully working now.

2024-05-31 22:25 UTC, EvilHero90 approved these changes
LGTM

2024-05-31 23:05 UTC, merged