Fix usage items under player
otland/forgottenserver pull request #4758
Opened 2024-06-21 15:51 UTC by ArturKnopik

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Fix usage items under player
https://github.com/otland/forgottenserver/issues/4001

### How to test
1. Put item under player, for example mana potion
2. Use item
-------------------------------------------------------
1. Stay under door
2. try close the door

Code author(probably): @Zbizu

2024-06-22 07:01 UTC, Zbizu commented
correct, original diff (private repo):
```diff
diff --git a/src/tile.cpp b/src/tile.cpp
index b748de0c2..5b42a8b8e 100644
--- a/src/tile.cpp
+++ b/src/tile.cpp
@@ -1606,12 +1606,31 @@ bool Tile::isMoveableBlocking() const
 Item* Tile::getUseItem(int32_t index) const
 {
 	const TileItemVector* items = getItemList();
+
+	// no items, get ground
 	if (!items || items->size() == 0) {
 		return ground;
 	}
 
+	// try getting thing by index
 	if (Thing* thing = getThing(index)) {
-		return thing->getItem();
+		Item* thingItem = thing->getItem();
+		if (thingItem) {
+			return thingItem;
+		}
+	}
+
+	// try getting top usable item
+	Item* topDownItem = getTopDownItem();
+	if (topDownItem) {
+		return topDownItem;
+	}
+
+	// try getting door
+	for (auto it = items->rbegin(), end = items->rend(); it != end; ++it) {
+		if ((*it)->getDoor()) {
+			return (*it)->getDoor();
+		}
 	}
 
 	return nullptr;
```

2024-06-23 18:51 UTC, ranisalt approved these changes

2024-06-23 19:02 UTC, EPuncker approved these changes

2024-06-25 13:14 UTC, Zbizu requested changes

2024-06-25 13:14 UTC, Zbizu commented on src/tile.cpp
> +	// try getting top usable item
top movable*

2024-06-25 13:14 UTC, Zbizu commented on src/tile.cpp
> +	return nullptr;
This needs to stay. It returns top immovable item.

2024-10-06 13:12 UTC, EPuncker approved these changes

2024-10-06 18:03 UTC, merged

2024-10-06 21:13 UTC, kaleohanopahala commented
Hmm would be:
It's prevent double interaction. 
Safe returns.

```
Item* Tile::getUseItem(int32_t index) const
{
	const TileItemVector* items = getItemList();

	// no items, return ground
	if (!items || items->empty()) {
		return ground;
	}

	// try getting thing by index if it's within bounds
	if (index >= 0 && index < static_cast<int32_t>(items->size())) {
		if (Thing* thing = getThing(index)) {
			Item* thingItem = thing->getItem();
			if (thingItem) {
				return thingItem;
			}
		}
	}

	// try getting top movable item
	Item* topDownItem = getTopDownItem();
	if (topDownItem) {
		return topDownItem;
	}

	// try getting door item
	for (auto it = items->rbegin(), end = items->rend(); it != end; ++it) {
		if ((*it)->getDoor()) {
			return (*it)->getItem();
		}
	}

	// fallback to first item in the list if items are present
	return !items->empty() ? *items->begin() : nullptr;
}
```