Fix light crash
otland/forgottenserver pull request #4806
Opened 2024-10-07 10:09 UTC by nekiro

### Pull Request Prelude

- [ ] I have followed [proper The Forgotten Server code styling][code].
- [ ] I have read and understood the [contribution guidelines][cont] before making this PR.
- [ ] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Ensure light level is always 1, optionally warn user about incorrect value being set

**Issues addressed:** 
Fix #4782

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2024-10-07 17:17 UTC, EPuncker approved these changes

2024-10-07 22:32 UTC, Codinablack requested changes

2024-10-07 22:32 UTC, Codinablack commented on src/condition.cpp
> +			lightInfo.level = std::max(1, value);
since lightinfo.level is a uint8_t and value is an int32_t, maybe we should go ahead and add some safety here and use clamp instead?

2024-10-08 00:19 UTC, ramon-bernardo commented
Could there also be validation in the lua core? https://github.com/otland/forgottenserver/blob/624e8884497cbdf8c1a56ae55e3eddedd55120e9/data/lib/core/game/world_light.lua#L18-L21

2024-10-08 07:39 UTC, nekiro commented
> Could there also be validation in the lua core?
> 
> https://github.com/otland/forgottenserver/blob/624e8884497cbdf8c1a56ae55e3eddedd55120e9/data/lib/core/game/world_light.lua#L18-L21

nah, it will still crash for the special people that like to break stuff, if source crashes it should be fixed in source imo

2024-10-08 15:06 UTC, merged