fix monster attack behavior
otland/forgottenserver pull request #4866
Opened 2024-12-04 13:19 UTC by ArturKnopik

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Fix monster attack behavior

**Issues addressed:** 
https://github.com/otland/forgottenserver/issues/4865

**How to test:** 
go to monsters/ create monsters:
Troll - hit to red, let them fleeing
Cyclops
Hunter 
Rabbit

2024-12-05 22:37 UTC, nekiro commented
imo there is missing updateFollowCreaturePath(fpp); after this code so specifically:

https://github.com/otland/forgottenserver/blob/a78d2ed78fab73069d429e18d4929f77aaf9db5c/src/monster.cpp#L606
```
} else {
    updateFollowCreaturePath(fpp);
}
```
genuinely sad this code was merged, its broken at the first sight when **joining the game and checking**

2024-12-07 19:22 UTC, ramon-bernardo commented
@nekiro I don't see where this `update` might be missing, as redundancies were removed (**highlighted in red**), and the logic was simplified (**highlighted in yellow**)

2024-12-11 13:22 UTC, ArturKnopik commented
@nekiro @ramon-bernardo, can you test my fix?

2024-12-21 11:43 UTC, nekiro requested changes

2024-12-21 11:43 UTC, nekiro commented on src/monster.cpp
> -		updateFollowCreaturePath(fpp);
use updateFollowCreaturePath
its the exact duplicate of the code you pasted here, so there is no reason to duplicate the code again

2024-12-21 11:43 UTC, nekiro commented on src/monster.cpp
> -				updateFollowCreaturePath(fpp);
same as previously, use this method as its the same code, so its okay

2024-12-21 15:39 UTC, ramon-bernardo commented
Unfortunately, i cant test it because my cip client doesn't connect to login server. I could try using OTClient, but not sure if it support v13

2024-12-29 18:53 UTC, nekiro approved these changes

2024-12-29 19:00 UTC, merged