Don't recreate stackables every move
otland/forgottenserver pull request #4873
Opened 2024-12-10 22:16 UTC by nekiro

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Follow up to #4761
Don't recreate stackables on every move, create new stackables only when really needed.

**Issues addressed:** 
Stackable items are recreated even when they shouldn't, if you move a full stack of stackable item, why would you create a new item and delete the old one?
This seems pretty wasteful and unnecessary.

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

**How to test:** 
Play with stackables

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

2024-12-17 17:24 UTC, Tofame approved these changes

2024-12-19 22:01 UTC, ArturKnopik approved these changes

2024-12-19 22:08 UTC, ArturKnopik requested changes
There is a case where it doesn't work 
1) put 99 gold to bp
2) kill troll
3) take gold from troll 
result: stack of gold is filled up to 100, rest of the gold disappear

2024-12-20 12:13 UTC, ArturKnopik requested changes
Stackables is not moved to destiny container if stack is filled up, rest of stackables stays in source container like monster body

2024-12-20 20:09 UTC, ArturKnopik approved these changes

2025-02-06 07:53 UTC, merged

2025-02-10 22:01 UTC, RevengeSpeed commented
@nekiro i have a project that takes up compiling, do you have any way to contact you a little more privately?